# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path to prepend to sys.path of the-running context.
# Defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value passed to Date.strftime()
# timezone =

# max length of characters to clone to slug.
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded with relative paths
# otherwise standard sys.path rules apply
# resolve_relative_path = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, paths must be separated by the version_path_separator char
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; defaults to 'os', which uses os.pathsep.
# can be written as a semicolon or space for clear multi-line configurations
# version_path_separator = :

# the encoding used for schema formatting
# output_encoding = utf-8

# database connection URL - we read this dynamically in env.py from settings,
# so we can keep it blank here.
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@db:5432/app


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
